/// # Data Schema and Serialization Layer
///
/// This module is the *source of truth* for all data structures that flow
/// through the Retiscope system.  It is deliberately split into two
/// layers:
///
/// 1. **Capture Schema** – `AnnounceData`  
///    Represents raw network announcements that are produced during
///    high‑throughput capture.  The struct is intentionally lightweight
///    and only contains the fields that must be serialised on the wire.
///
/// 2. **Persistence Schema** – `StoredAnnounce` and `StoredNode`  
///    Enriches the raw data with database‑specific metadata such as
///    autogenerated `id` values, timestamps (`first_seen`, `last_seen`),
///    and the `timestamp` of the original capture.  These structs are
///    used only when the data is written to or read from a database.
///
/// The two schemas are connected by custom *Serde* logic that converts
/// the domain‑specific `AddressHash` type to and from hex‑encoded
/// strings.  The conversion is **transparent** to callers and allows
/// us to keep the Rust type system clean while still storing data
/// in a compact, human‑readable form.
///
/// ## Custom Serde Logic
///
/// * **Hex‑String Mapping** –  
///   `AddressHash::to_hex_string()` is used for serialization, and
///   `AddressHash::new_from_hex_string()` for deserialization.  
///   The hex strings may optionally be prefixed by a colon (e.g.
///   `":abcdef"`).  The prefix is stripped during deserialization to
///   keep the database representation flexible.
///
/// * **Optional Handling** –  
///   `transport_node` in `AnnounceData` is an `Option<AddressHash>`.  
///   The custom visitor (`OptHashVisitor`) accepts any representation
///   (string, `null`, or missing field) and normalises it to an
///   `Option<AddressHash>`.  If the field is absent or `null`, the
///   value is `None`.
///
/// * **Error Mapping** –  
///   Deserialization failures (e.g. malformed hex strings) are mapped
///   to `RetiscopeError::FailedToParse`.  The visitor returns
///   `serde::de::Error::custom(...)` so that callers see a clear,
///   typed error.
#[allow(unused_imports)]
use tracing::{debug, error, info, instrument, trace, warn};

use crate::errors::RetiscopeError;

use reticulum::hash::AddressHash;
use serde::{de, Deserialize, Deserializer, Serialize, Serializer};

pub mod database;

/// Raw announcement captured from the network.
/// Keeps only the minimal data needed for high‑throughput ingestion.
#[allow(dead_code)]
#[derive(Clone, Serialize)]
pub struct AnnounceData {
    /// Number of hops the packet travelled.
    pub hops: u8,

    /// Optional transport node that forwarded the packet.
    #[serde(
        skip_serializing_if = "Option::is_none",
        serialize_with = "serialize_opt_hash"
    )]
    pub transport_node: Option<AddressHash>,

    /// Destination of the announcement.
    #[serde(serialize_with = "serialize_hash")]
    pub destination: AddressHash,

    /// Interface that received the announcement.
    #[serde(serialize_with = "serialize_hash")]
    pub iface: AddressHash,
}

/// Persisted announcement stored in the database.
/// Includes capture metadata (`id`, `timestamp`) and deserialisation helpers.
#[derive(Debug, Clone, Deserialize)]
pub struct StoredAnnounce {
    /// Auto‑generated database identifier.
    pub id: String,

    /// Number of hops the packet travelled.
    pub hops: u8,

    /// Optional transport node that forwarded the packet.
    #[serde(default, deserialize_with = "deserialize_opt_hash")]
    pub transport_node: Option<AddressHash>,

    /// Destination of the announcement.
    #[serde(deserialize_with = "deserialize_hash")]
    pub destination: AddressHash,

    /// Interface that generated the announcement.
    #[serde(deserialize_with = "deserialize_hash")]
    pub iface: AddressHash,

    /// Timestamp of when the announcement was first captured.
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

/// Minimal node record kept in the database.
/// Stores the first and last time the node was observed.
#[derive(Debug, Clone, Deserialize)]
pub struct StoredNode {
    /// Auto‑generated database identifier.
    pub id: String,

    /// When the node was first seen.
    pub first_seen: chrono::DateTime<chrono::Utc>,

    /// Most recent time the node was observed.
    pub last_seen: chrono::DateTime<chrono::Utc>,
}

fn serialize_hash<S>(hash: &AddressHash, ser: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    ser.serialize_str(&hash.to_hex_string())
}

fn serialize_opt_hash<S>(opt: &Option<AddressHash>, ser: S) -> Result<S::Ok, S::Error>
where
    S: Serializer,
{
    match opt {
        Some(h) => ser.serialize_str(&h.to_hex_string()),
        None => ser.serialize_none(),
    }
}

fn deserialize_opt_hash<'de, D>(de: D) -> Result<Option<AddressHash>, D::Error>
where
    D: Deserializer<'de>,
{
    struct OptHashVisitor;
    impl<'de> de::Visitor<'de> for OptHashVisitor {
        type Value = Option<AddressHash>;
        fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.write_str("an optional hex string")
        }
        fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            let hex = v.splitn(2, ':').last().unwrap_or(v);
            AddressHash::new_from_hex_string(hex)
                .map(Some)
                .map_err(|_| de::Error::custom(RetiscopeError::FailedToParse))
        }
        fn visit_some<D2>(self, deserializer: D2) -> Result<Self::Value, D2::Error>
        where
            D2: Deserializer<'de>,
        {
            deserializer.deserialize_str(self)
        }
        fn visit_none<E>(self) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(None)
        }
        fn visit_unit<E>(self) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            Ok(None)
        }
    }
    de.deserialize_any(OptHashVisitor) // deserialize_any instead of deserialize_option
}

fn deserialize_hash<'de, D>(de: D) -> Result<AddressHash, D::Error>
where
    D: Deserializer<'de>,
{
    struct HashVisitor;
    impl<'de> de::Visitor<'de> for HashVisitor {
        type Value = AddressHash;

        fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.write_str("a hex string")
        }

        fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
        where
            E: de::Error,
        {
            let hex = v.splitn(2, ':').last().unwrap_or(v);
            AddressHash::new_from_hex_string(hex)
                .map_err(|_| de::Error::custom(RetiscopeError::FailedToParse))
        }
    }

    de.deserialize_str(HashVisitor)
}
